import { Combobox } from '@/components/ui/combobox'

const timezones = [
  { value: 'pacific_niue', label: 'Pacific/Niue', offset: 'GMT-11:00' },
  { value: 'pacific_pago_pago', label: 'Pacific/Pago_Pago', offset: 'GMT-11:00' },
  { value: 'pacific_honolulu', label: 'Pacific/Honolulu', offset: 'GMT-10:00' },
  { value: 'america_adak', label: 'America/Adak', offset: 'GMT-10:00' },
  { value: 'america_anchorage', label: 'America/Anchorage', offset: 'GMT-09:00' },
  { value: 'america_juneau', label: 'America/Juneau', offset: 'GMT-09:00' },
  { value: 'america_los_angeles', label: 'America/Los_Angeles', offset: 'GMT-08:00' },
  { value: 'america_vancouver', label: 'America/Vancouver', offset: 'GMT-08:00' },
  { value: 'america_denver', label: 'America/Denver', offset: 'GMT-07:00' },
  { value: 'america_phoenix', label: 'America/Phoenix', offset: 'GMT-07:00' },
  { value: 'america_chicago', label: 'America/Chicago', offset: 'GMT-06:00' },
  { value: 'america_mexico_city', label: 'America/Mexico_City', offset: 'GMT-06:00' },
  { value: 'america_new_york', label: 'America/New_York', offset: 'GMT-05:00' },
  { value: 'america_bogota', label: 'America/Bogota', offset: 'GMT-05:00' },
  { value: 'america_halifax', label: 'America/Halifax', offset: 'GMT-04:00' },
  { value: 'america_santiago', label: 'America/Santiago', offset: 'GMT-04:00' },
  { value: 'america_st_johns', label: 'America/St_Johns', offset: 'GMT-03:30' },
  { value: 'america_sao_paulo', label: 'America/Sao_Paulo', offset: 'GMT-03:00' },
  {
    value: 'america_argentina_buenos_aires',
    label: 'America/Argentina/Buenos_Aires',
    offset: 'GMT-03:00',
  },
  { value: 'america_noronha', label: 'America/Noronha', offset: 'GMT-02:00' },
  { value: 'atlantic_south_georgia', label: 'Atlantic/South_Georgia', offset: 'GMT-02:00' },
  { value: 'atlantic_azores', label: 'Atlantic/Azores', offset: 'GMT-01:00' },
  { value: 'atlantic_cape_verde', label: 'Atlantic/Cape_Verde', offset: 'GMT-01:00' },
  { value: 'europe_london', label: 'Europe/London', offset: 'GMT+00:00' },
  { value: 'africa_casablanca', label: 'Africa/Casablanca', offset: 'GMT+00:00' },
  { value: 'europe_berlin', label: 'Europe/Berlin', offset: 'GMT+01:00' },
  { value: 'africa_lagos', label: 'Africa/Lagos', offset: 'GMT+01:00' },
  { value: 'europe_helsinki', label: 'Europe/Helsinki', offset: 'GMT+02:00' },
  { value: 'africa_cairo', label: 'Africa/Cairo', offset: 'GMT+02:00' },
  { value: 'europe_moscow', label: 'Europe/Moscow', offset: 'GMT+03:00' },
  { value: 'asia_riyadh', label: 'Asia/Riyadh', offset: 'GMT+03:00' },
  { value: 'asia_dubai', label: 'Asia/Dubai', offset: 'GMT+04:00' },
  { value: 'asia_baku', label: 'Asia/Baku', offset: 'GMT+04:00' },
  { value: 'asia_kabul', label: 'Asia/Kabul', offset: 'GMT+04:30' },
  { value: 'asia_tehran', label: 'Asia/Tehran', offset: 'GMT+04:30' },
  { value: 'asia_karachi', label: 'Asia/Karachi', offset: 'GMT+05:00' },
  { value: 'asia_tashkent', label: 'Asia/Tashkent', offset: 'GMT+05:00' },
  { value: 'asia_kolkata', label: 'Asia/Kolkata', offset: 'GMT+05:30' },
  { value: 'asia_colombo', label: 'Asia/Colombo', offset: 'GMT+05:30' },
  { value: 'asia_kathmandu', label: 'Asia/Kathmandu', offset: 'GMT+05:45' },
  { value: 'asia_dhaka', label: 'Asia/Dhaka', offset: 'GMT+06:00' },
  { value: 'asia_almaty', label: 'Asia/Almaty', offset: 'GMT+06:00' },
  { value: 'asia_rangoon', label: 'Asia/Rangoon', offset: 'GMT+06:30' },
  { value: 'asia_bangkok', label: 'Asia/Bangkok', offset: 'GMT+07:00' },
  { value: 'asia_ho_chi_minh', label: 'Asia/Ho_Chi_Minh', offset: 'GMT+07:00' },
  { value: 'asia_shanghai', label: 'Asia/Shanghai', offset: 'GMT+08:00' },
  { value: 'asia_singapore', label: 'Asia/Singapore', offset: 'GMT+08:00' },
  { value: 'asia_tokyo', label: 'Asia/Tokyo', offset: 'GMT+09:00' },
  { value: 'asia_seoul', label: 'Asia/Seoul', offset: 'GMT+09:00' },
  { value: 'australia_adelaide', label: 'Australia/Adelaide', offset: 'GMT+09:30' },
  { value: 'australia_darwin', label: 'Australia/Darwin', offset: 'GMT+09:30' },
  { value: 'australia_sydney', label: 'Australia/Sydney', offset: 'GMT+10:00' },
  { value: 'australia_brisbane', label: 'Australia/Brisbane', offset: 'GMT+10:00' },
  { value: 'pacific_noumea', label: 'Pacific/Noumea', offset: 'GMT+11:00' },
  { value: 'pacific_guadalcanal', label: 'Pacific/Guadalcanal', offset: 'GMT+11:00' },
  { value: 'pacific_auckland', label: 'Pacific/Auckland', offset: 'GMT+12:00' },
  { value: 'pacific_fiji', label: 'Pacific/Fiji', offset: 'GMT+12:00' },
  { value: 'pacific_fakaofo', label: 'Pacific/Fakaofo', offset: 'GMT+13:00' },
  { value: 'pacific_tongatapu', label: 'Pacific/Tongatapu', offset: 'GMT+13:00' },
  { value: 'pacific_kiritimati', label: 'Pacific/Kiritimati', offset: 'GMT+14:00' },
]

export default function TimezoneCombobox({
  form,
  field,
}: {
  form: { setValue: (key: string, value: any) => void }
  field: { value: Date | string | null }
}) {
  return <Combobox valueName="timezone" items={timezones} form={form} field={field} />
}
